[run]
build = "npm run build"

[gptengineer-app]
project_id = "97d1b519-41db-4f68-9e23-bbc0b31d0c3f"

[[gptengineer-app.openapi]]
url = "http://e"

[[gptengineer-app.openapi]]
url = "http://b"

[[gptengineer-app.openapi]]
url = "http://c"
